/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AuthLoginImport } from './routes/auth/login'
import { Route as AuthLayoutImport } from './routes/auth/_layout'
import { Route as websiteLayoutImport } from './routes/(website)/_layout'
import { Route as websiteLayoutIndexImport } from './routes/(website)/_layout/index'
import { Route as websiteLayoutContectImport } from './routes/(website)/_layout/contect'
import { Route as websiteLayoutAboutImport } from './routes/(website)/_layout/about'

// Create Virtual Routes

const AuthImport = createFileRoute('/auth')()
const websiteImport = createFileRoute('/(website)')()

// Create/Update Routes

const AuthRoute = AuthImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRoute,
} as any)

const websiteRoute = websiteImport.update({
  id: '/(website)',
  getParentRoute: () => rootRoute,
} as any)

const AuthLoginRoute = AuthLoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)

const AuthLayoutRoute = AuthLayoutImport.update({
  id: '/_layout',
  getParentRoute: () => AuthRoute,
} as any)

const websiteLayoutRoute = websiteLayoutImport.update({
  id: '/_layout',
  getParentRoute: () => websiteRoute,
} as any)

const websiteLayoutIndexRoute = websiteLayoutIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => websiteLayoutRoute,
} as any)

const websiteLayoutContectRoute = websiteLayoutContectImport.update({
  id: '/contect',
  path: '/contect',
  getParentRoute: () => websiteLayoutRoute,
} as any)

const websiteLayoutAboutRoute = websiteLayoutAboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => websiteLayoutRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(website)': {
      id: '/(website)'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof websiteImport
      parentRoute: typeof rootRoute
    }
    '/(website)/_layout': {
      id: '/(website)/_layout'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof websiteLayoutImport
      parentRoute: typeof websiteRoute
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthImport
      parentRoute: typeof rootRoute
    }
    '/auth/_layout': {
      id: '/auth/_layout'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthLayoutImport
      parentRoute: typeof AuthRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginImport
      parentRoute: typeof AuthImport
    }
    '/(website)/_layout/about': {
      id: '/(website)/_layout/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof websiteLayoutAboutImport
      parentRoute: typeof websiteLayoutImport
    }
    '/(website)/_layout/contect': {
      id: '/(website)/_layout/contect'
      path: '/contect'
      fullPath: '/contect'
      preLoaderRoute: typeof websiteLayoutContectImport
      parentRoute: typeof websiteLayoutImport
    }
    '/(website)/_layout/': {
      id: '/(website)/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof websiteLayoutIndexImport
      parentRoute: typeof websiteLayoutImport
    }
  }
}

// Create and export the route tree

interface websiteLayoutRouteChildren {
  websiteLayoutAboutRoute: typeof websiteLayoutAboutRoute
  websiteLayoutContectRoute: typeof websiteLayoutContectRoute
  websiteLayoutIndexRoute: typeof websiteLayoutIndexRoute
}

const websiteLayoutRouteChildren: websiteLayoutRouteChildren = {
  websiteLayoutAboutRoute: websiteLayoutAboutRoute,
  websiteLayoutContectRoute: websiteLayoutContectRoute,
  websiteLayoutIndexRoute: websiteLayoutIndexRoute,
}

const websiteLayoutRouteWithChildren = websiteLayoutRoute._addFileChildren(
  websiteLayoutRouteChildren,
)

interface websiteRouteChildren {
  websiteLayoutRoute: typeof websiteLayoutRouteWithChildren
}

const websiteRouteChildren: websiteRouteChildren = {
  websiteLayoutRoute: websiteLayoutRouteWithChildren,
}

const websiteRouteWithChildren =
  websiteRoute._addFileChildren(websiteRouteChildren)

interface AuthRouteChildren {
  AuthLayoutRoute: typeof AuthLayoutRoute
  AuthLoginRoute: typeof AuthLoginRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLayoutRoute: AuthLayoutRoute,
  AuthLoginRoute: AuthLoginRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof websiteLayoutIndexRoute
  '/auth': typeof AuthLayoutRoute
  '/auth/login': typeof AuthLoginRoute
  '/about': typeof websiteLayoutAboutRoute
  '/contect': typeof websiteLayoutContectRoute
}

export interface FileRoutesByTo {
  '/auth': typeof AuthLayoutRoute
  '/auth/login': typeof AuthLoginRoute
  '/about': typeof websiteLayoutAboutRoute
  '/contect': typeof websiteLayoutContectRoute
  '/': typeof websiteLayoutIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/(website)': typeof websiteRouteWithChildren
  '/(website)/_layout': typeof websiteLayoutRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/auth/_layout': typeof AuthLayoutRoute
  '/auth/login': typeof AuthLoginRoute
  '/(website)/_layout/about': typeof websiteLayoutAboutRoute
  '/(website)/_layout/contect': typeof websiteLayoutContectRoute
  '/(website)/_layout/': typeof websiteLayoutIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/auth' | '/auth/login' | '/about' | '/contect'
  fileRoutesByTo: FileRoutesByTo
  to: '/auth' | '/auth/login' | '/about' | '/contect' | '/'
  id:
    | '__root__'
    | '/(website)'
    | '/(website)/_layout'
    | '/auth'
    | '/auth/_layout'
    | '/auth/login'
    | '/(website)/_layout/about'
    | '/(website)/_layout/contect'
    | '/(website)/_layout/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  websiteRoute: typeof websiteRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  websiteRoute: websiteRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/(website)",
        "/auth"
      ]
    },
    "/(website)": {
      "filePath": "(website)",
      "children": [
        "/(website)/_layout"
      ]
    },
    "/(website)/_layout": {
      "filePath": "(website)/_layout.tsx",
      "parent": "/(website)",
      "children": [
        "/(website)/_layout/about",
        "/(website)/_layout/contect",
        "/(website)/_layout/"
      ]
    },
    "/auth": {
      "filePath": "auth",
      "children": [
        "/auth/_layout",
        "/auth/login"
      ]
    },
    "/auth/_layout": {
      "filePath": "auth/_layout.tsx",
      "parent": "/auth"
    },
    "/auth/login": {
      "filePath": "auth/login.tsx",
      "parent": "/auth"
    },
    "/(website)/_layout/about": {
      "filePath": "(website)/_layout/about.tsx",
      "parent": "/(website)/_layout"
    },
    "/(website)/_layout/contect": {
      "filePath": "(website)/_layout/contect.tsx",
      "parent": "/(website)/_layout"
    },
    "/(website)/_layout/": {
      "filePath": "(website)/_layout/index.tsx",
      "parent": "/(website)/_layout"
    }
  }
}
ROUTE_MANIFEST_END */
